# Generated by Django 3.2.16 on 2023-12-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_file_data',
            name='owner',
            field=models.BooleanField(default=True),
        ),
    ]
