# Generated by Django 3.2.16 on 2023-12-10 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_share', '0003_alter_user_file_data_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_file_data',
            name='owner',
        ),
    ]
